# Generated by Django 4.2 on 2024-04-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_alter_user_email_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='client',
            new_name='user',
        ),
    ]
